# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wordgame_pb2 as protos_dot_wordgame__pb2


class GameStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChoosePhrase = channel.unary_unary(
                '/wordgame.Game/ChoosePhrase',
                request_serializer=protos_dot_wordgame__pb2.PhraseRequest.SerializeToString,
                response_deserializer=protos_dot_wordgame__pb2.PhraseResultReply.FromString,
                )
        self.InitializePhrase = channel.unary_unary(
                '/wordgame.Game/InitializePhrase',
                request_serializer=protos_dot_wordgame__pb2.InitRequest.SerializeToString,
                response_deserializer=protos_dot_wordgame__pb2.InitResultReply.FromString,
                )
        self.ChangeLetter = channel.unary_unary(
                '/wordgame.Game/ChangeLetter',
                request_serializer=protos_dot_wordgame__pb2.LetterRequest.SerializeToString,
                response_deserializer=protos_dot_wordgame__pb2.LetterResultReply.FromString,
                )


class GameServicer(object):
    """The greeting service definition.
    """

    def ChoosePhrase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializePhrase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeLetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChoosePhrase': grpc.unary_unary_rpc_method_handler(
                    servicer.ChoosePhrase,
                    request_deserializer=protos_dot_wordgame__pb2.PhraseRequest.FromString,
                    response_serializer=protos_dot_wordgame__pb2.PhraseResultReply.SerializeToString,
            ),
            'InitializePhrase': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializePhrase,
                    request_deserializer=protos_dot_wordgame__pb2.InitRequest.FromString,
                    response_serializer=protos_dot_wordgame__pb2.InitResultReply.SerializeToString,
            ),
            'ChangeLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeLetter,
                    request_deserializer=protos_dot_wordgame__pb2.LetterRequest.FromString,
                    response_serializer=protos_dot_wordgame__pb2.LetterResultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordgame.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """The greeting service definition.
    """

    @staticmethod
    def ChoosePhrase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wordgame.Game/ChoosePhrase',
            protos_dot_wordgame__pb2.PhraseRequest.SerializeToString,
            protos_dot_wordgame__pb2.PhraseResultReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitializePhrase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wordgame.Game/InitializePhrase',
            protos_dot_wordgame__pb2.InitRequest.SerializeToString,
            protos_dot_wordgame__pb2.InitResultReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wordgame.Game/ChangeLetter',
            protos_dot_wordgame__pb2.LetterRequest.SerializeToString,
            protos_dot_wordgame__pb2.LetterResultReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
