# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wordgame_pb2 as protos_dot_wordgame__pb2


class GameStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GuessingLetter = channel.unary_unary(
                '/wordgame.Game/GuessingLetter',
                request_serializer=protos_dot_wordgame__pb2.LetterRequest.SerializeToString,
                response_deserializer=protos_dot_wordgame__pb2.ResultReply.FromString,
                )


class GameServicer(object):
    """The greeting service definition.
    """

    def GuessingLetter(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GuessingLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.GuessingLetter,
                    request_deserializer=protos_dot_wordgame__pb2.LetterRequest.FromString,
                    response_serializer=protos_dot_wordgame__pb2.ResultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordgame.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """The greeting service definition.
    """

    @staticmethod
    def GuessingLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wordgame.Game/GuessingLetter',
            protos_dot_wordgame__pb2.LetterRequest.SerializeToString,
            protos_dot_wordgame__pb2.ResultReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
