# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/wordgame.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/wordgame.proto\x12\x08wordgame\"\x1f\n\rLetterRequest\x12\x0e\n\x06letter\x18\x01 \x01(\t\"\x1d\n\x0bResultReply\x12\x0e\n\x06result\x18\x01 \x01(\t2J\n\x04Game\x12\x42\n\x0eGuessingLetter\x12\x17.wordgame.LetterRequest\x1a\x15.wordgame.ResultReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.wordgame_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LETTERREQUEST._serialized_start=35
  _LETTERREQUEST._serialized_end=66
  _RESULTREPLY._serialized_start=68
  _RESULTREPLY._serialized_end=97
  _GAME._serialized_start=99
  _GAME._serialized_end=173
# @@protoc_insertion_point(module_scope)
